spring:
  config:
    activate:
      on-profile: secret

naver:
  datalab:
    client-id: "vASJJv1_EwI6_j5YCy7E"
    client-secret: "H8sO3rwShL"

  ad:
    api-key: "0100000000291a3af033d5216de65fa3bc9a0652425938934ddd780921ddd6866ccb815ddb"
    customer-id: "1804538"
    secret-key:  "AQAAAAApGjrwM9UhbeZfo7yaBlJChBxZ4ZtJnWxMh/fhUAvxYw=="


